### ISSUE TITLE
In Pick, if using option Prompt For Qty, if you enter a higher number, there is no error and the higher number is not recorded in CB

### ISSUE THREAD

**Issue by davidonelson** [DynEntTech/connectedwarehouse#10]
https://github.com/connectedbusiness/connectedwarehouse/issues/13

In Pick, if using option Prompt For Qty, if you enter a higher number than was was ordered, provide an error and don't consider the item to be picked.  (We can adjust this requirement if needed.  But as of now, if the order is 5 and you pick and enter 10, CB gets update with 5 picked and there is no indication of a problem, which is not good.)

**Comment by davidonelson** [comment]
recording of issue posted on CB issue

**Comment by davidonelson** [comment]
See video here for details:  https://youtu.be/HRcRk0N9xuU

PART A:  Change text in popup
1. Change text "index.html" to "Remaining Quantity Exceeded"
2. Change text "Please enter less quantity" to "Enter X or less" (where X is the quantity remaining to be picked)

PART B: Defect
pressing "enter" second time does not show message again
pressing on some numbers results in no action on screen
After I get the new message, it seems like every other key press does nothing

**Comment by Surinderkaur329** [comment]
ok

**Comment by davidonelson** [comment]
PROBLEM WITH MESSAGE TEXT

PART A subsection 2 from above needs to be fixed

When I said "(where X is the quantity remaining to be picked)", this was a comment to you only, this text was not to appear on the screen.  This text needs to be removed from the popup text.

When I said "Enter X or less" this was to appear on the screen, but X was to be replaced with the quantity remaining to be picked, so the user knows the maximum quantity that can be entered on the screen.

Currently you are displaying "Enter X or less".  The message should say "Enter 6 or less" if the quantity remaining is 6.  The message should say "Enter 5 or less" if the quantity remaining is 5, etc

**Comment by Surinderkaur329** [comment]
ok
