### ISSUE TITLE
In Pick, on the item detail, why does the item name sometimes turn dark blue in color?

### ISSUE THREAD

**Issue by davidonelson** [DynEntTech/connectedwarehouse#13]
https://github.com/connectedbusiness/connectedwarehouse/issues/26

When the form is first displayed, the item name is white and readable, but very quickly, sometimes, the item name then turns dark blue and unreadable.

What condition causes the item name to turn dark blue?

Since the item name is unreadable when it turns dark blue, it seems to me it should always be white.

![image](https://user-images.githubusercontent.com/453837/69831130-e58e3180-11dc-11ea-94dd-1318f1750a0c.png)

**Comment by davidonelson** [comment]
See recording of issue:  https://youtu.be/mLbtDEAq8k0

**Comment by Surinderkaur329** [comment]
Done

**Comment by davidonelson** [comment]
Also in testing today I found the UPC code is turning dark blue sometimes (and then becomes unreadable)

**Comment by davidonelson** [comment]
REQUEST 1:
You provided this answer in an email "its based on shipping unit quantity".  However, this is not enough information for me to use for decision making.  Please provide the exact rules from the code that is causing the code to change blue.

REQUEST 2:
I am thinking of eliminating the changing of the color to blue.  Please answer this questions (a) Do you have any idea why the programmer is turning the color to blue?  (b) Can you think of any disadvantage to keeping the color white always?

**Comment by Surinderkaur329** [comment]
REQUEST 1:
You provided this answer in an email "its based on shipping unit quantity". However, this is not enough information for me to use for decision making. Please provide the exact rules from the code that is causing the code to change blue.

Ans: 
![Shipping-notes](https://user-images.githubusercontent.com/13986893/72163255-7ca7f500-33e9-11ea-9d6c-3e1ea3c52e92.png)


REQUEST 2:
I am thinking of eliminating the changing of the color to blue. Please answer this questions (a) Do you have any idea why the programmer is turning the color to blue? (b) Can you think of any disadvantage to keeping the color white always?

**Ans: (a)  As per the code review there must be css issue to change the color to blue.
Ans: (b) There is not any disadvantage to keep color the white as it will show in any condition but blue will have visibility issue for some users.

I just recommended to keep white as it will show in all screens.

Further in future if we find any issue we can change anytime as its all code in our hand.**

**Comment by davidonelson** [comment]
Understood.  I created this new issue to make the change you suggested: https://github.com/DynEntTech/connectedwarehouse/issues/18
