### ISSUE TITLE
In Pick, upon exit out of the middle of a pick, allow "Save" or "Cancel" (instead of just cancel) 

### ISSUE THREAD

**Issue by davidonelson** [DynEntTech/connectedwarehouse#6]
https://github.com/connectedbusiness/connectedwarehouse/issues/14

**Comment by Surinderkaur329** [comment]
Done.

**Comment by davidonelson** [comment]
IS not fixed in "warehouse version 2.2.0 surinder kaur"

**Comment by davidonelson** [comment]
is not fixed in "version 3.0.0"

**Comment by davidonelson** [comment]
As this is a complex change, and it is not in the release yet, I think it best (a) revert/comment out any changes you made for this issue (but you could save them somewhere if desired) (b) flag issue issue as on hold (c) Get all other issues solved and committed to CB source code, then come back to this later.

**Comment by deti-sandeep** [comment]
Saved is only allowed in case of setting Pick >> Auto Complete is false.
