### ISSUE TITLE
In Bin Inventory module, show the item description in the list after selecting the bin number

### ISSUE THREAD

**Issue by davidonelson** [DynEntTech/connectedwarehouse#8]
https://github.com/connectedbusiness/connectedwarehouse/issues/5

**Comment by Surinderkaur329** [comment]
Done. 


![image](https://user-images.githubusercontent.com/13986893/62562460-d5092280-b89e-11e9-983c-c8755474367b.png)

**Comment by davidonelson** [comment]
Q/A APPROVED
